export default {
	properties: [
		{
			text: 'N°',
			key: 'num',
			type: 'text',
			value: '',
			not_show_on_form: true,
			show: true,
		},
		{
			text: 'Nombre',
			key: 'nombre',
			type: 'text',
			value: '',
			is_title: true,
		},
		{
			text: 'Factura compra asegurado',
			key: 'foto_factura_compra_asegurado',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Factura tecnico asegurado',
			key: 'foto_factura_tecnico_asegurado',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Factura tecnico scrap free',
			key: 'foto_factura_tecnico_scrap_free',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto adicional asegurado',
			key: 'foto_adicional_asegurado',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto atras asegurado',
			key: 'foto_atras_asegurado',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto atras tecnico scrap free',
			key: 'foto_atras_tecnico_scrap_free',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto evidencia scrap free',
			key: 'foto_evidencia_scrap_free',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto frente asegurado',
			key: 'foto_frente_asegurado',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto frente scrap free',
			key: 'foto_frente_tecnico_scrap_free',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto etiqueta',
			key: 'foto_etiqueta',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Foto captura de pantalla',
			key: 'foto_captura_de_pantalla',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Causa bien',
			key: 'causa_bien_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Estado bien',
			key: 'estado_bien_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Linea',
			key: 'linea_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Sub Linea',
			key: 'sub_linea_id',
			depends_on: 'linea_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Tecnico asegurado',
			key: 'tecnico_asegurado_id',
			store: 'tecnico',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Tecnico scrap free',
			key: 'tecnico_scrap_free_id',
			store: 'tecnico',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Accesorios',
			key: 'accesorios',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'Tiene base',
			key: 'tiene_base',
			type: 'checkbox',
			value: 0,
			show: true,
		},
		{
			text: 'Tiene cable',
			key: 'tiene_cable',
			type: 'checkbox',
			value: 0,
			show: true,
		},
		{
			text: 'Tiene cargador',
			key: 'tiene_cargador',
			type: 'checkbox',
			value: 0,
			show: true,
		},
		{
			text: 'Tiene control',
			key: 'tiene_control',
			type: 'checkbox',
			value: 0,
			show: true,
		},
		{
			text: 'Comentarios tecnico',
			key: 'comentarios_tecnico',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'Descripcion',
			key: 'descripcion',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'Fecha compra',
			key: 'fecha_compra',
			type: 'date',
			is_date: true,
			value: '',
			show: true,
		},
		{
			text: 'Informe tecnico asegurado',
			key: 'informe_tecnico_asegurado',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'Marca',
			key: 'marca',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'modelo',
			key: 'modelo',
			type: 'text',
			value: '',
			show: true,
		},
		{
			key: 'numero_serie',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'notas',
			key: 'notas',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'pagado tecnico',
			key: 'pagado_tecnico',
			type: 'number',
			value: '',
			show: true,
		},
		{
			text: 'Posible causa asegurado',
			key: 'posible_causa_asegurado',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'precisa embalaje',
			key: 'precisa_embalaje',
			type: 'checkbox',
			value: 0,
			show: true,
		},
		{
			text: 'presupuesto monto asegurado',
			key: 'presupuesto_monto_asegurado',
			type: 'number',
			value: '',
			show: true,
		},
		{
			text: 'liquidacion bien',
			key: 'liquidacion_bien',
			type: 'number',
			value: '',
			show: true,
		},
		{
			text: 'liquidacion deducible',
			key: 'liquidacion_deducible',
			type: 'number',
			value: '',
			show: true,
		},
		{
			text: 'liquidacion paga asegurado',
			key: 'liquidacion_paga_asegurado',
			type: 'number',
			value: '',
			show: true,
		},
		{
			text: 'valor reposicion a nuevo',
			key: 'valor_reposicion_a_nuevo',
			type: 'number',
			value: '',
			show: true,
		},
	],
	plural_model_name_spanish: 'Bienes',
	singular_model_name_spanish: 'Bien',
	create_model_name_spanish: 'Nuevo',
	text_delete: 'este',
}