export default {
	properties: [
		{
			text: 'N°',
			key: 'num',
			type: 'text',
			value: '',
			not_show_on_form: true,
			show: true,
		},
		{
			text: 'Asegurado',
			key: 'asegurado_id',
			type: 'search',
			value: '',
			is_title: true,
		},
		{
			text: 'Aseguradora',
			key: 'aseguradora_id',
			type: 'search',
			value: '',
			show: true,
			// is_between: {
			// 	parent_model_prop: 'asegurado',
			// 	model_prop: 'aseguradoras',
			// }
		},
		{
			text: 'Causa siniestro',
			key: 'causa_siniestro_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Estado general del siniestro',
			key: 'estado_general_siniestro_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Estado siniestro',
			key: 'estado_siniestro_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Historial Estados siniestro',
			key: 'estado_siniestros',
			store: 'estado_siniestro',
			belongs_to_many: {
				can_not_modify: true,
			},
		},
		{
			text: 'Provincia',
			key: 'provincia_id',
			type: 'search',
			value: 0,
			show: true,
		},
		{
			text: 'Localidad',
			key: 'localidad_id',
			depends_on: 'provincia_id',
			type: 'search',
			value: 0,
			show: true,
		},
		{
			text: 'Tipo de orden de Servicio',
			key: 'tipo_orden_de_servicio_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Gestor Scrap Free',
			key: 'gestor_scrap_free_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Gestor Aseguradora',
			key: 'gestor_aseguradora_id',
			type: 'select',
			value: 0,
			show: true,
		},
		{
			text: 'Codigo postal',
			key: 'codigo_postal',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'Comentarios seguro',
			key: 'comentarios_seguro',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'Costo reporte',
			key: 'costo_reporte',
			type: 'number',
			value: '',
			show: true,
		},
		{
			text: 'Bienes',
			key: 'bienes',
			has_many: {
				model_name: 'bien',
			}
		},
		{
			text: 'Logisticas',
			key: 'logisticas',
			has_many: {
				model_name: 'logistica',
			}
		},
		{
			text: 'Denunciante',
			key: 'denunciante',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'Foto deposito deducible',
			key: 'foto_deposito_deducible',
			type: 'image',
			value: '',
			show: true,
		},
		{
			text: 'Domicilio completo Google',
			key: 'domicilio_completo_google',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'Entre calles',
			key: 'entre_calles',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'Fecha alta en Scrap Free',
			key: 'fecha_alta_scrap_free',
			type: 'date',
			value: '',
			show: true,
		},
		{
			text: 'Fecha cierre administrativo',
			key: 'fecha_cierre_administrativo',
			type: 'date',
			value: '',
			show: true,
		},
		{
			text: 'Fecha cierre aseguradora',
			key: 'fecha_cierre_aseguradora',
			type: 'date',
			value: '',
			show: true,
		},
		{
			text: 'Fecha cierre scrap free',
			key: 'fecha_cierre_scrap_free',
			type: 'date',
			value: '',
			show: true,
		},
		{
			text: 'Fecha denuncia',
			key: 'fecha_denuncia',
			type: 'date',
			value: '',
			show: true,
		},
		{
			text: 'Fecha ocurrencia',
			key: 'fecha_ocurrencia',
			type: 'date',
			value: '',
			show: true,
		},
		{
			text: 'Liquidacion deducible',
			key: 'liquidacion_deducible',
			type: 'number',
			value: '',
			is_price: true,
			show: true,
		},
		{
			text: 'Liquidacion siniestro',
			key: 'liquidacion_siniestro',
			type: 'number',
			value: '',
			is_price: true,
			show: true,
		},
		{
			text: 'Notas domicilio',
			key: 'notas_domicilio',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'N° Orden servicio',
			key: 'orden_servicio',
			type: 'text',
			value: '',
			show: true,
		},
		{
			text: 'Recomendacion',
			key: 'recomendacion',
			type: 'textarea',
			value: '',
			show: true,
		},
		{
			text: 'Reparacion Deducible',
			key: 'reparacion_deducible',
			type: 'number',
			value: '',
			is_price: true,
			show: true,
		},
		{
			text: 'Reparacion paga asegurado',
			key: 'reparacion_paga_asegurado',
			type: 'number',
			value: '',
			is_price: true,
			show: true,
		},
		{
			text: 'Reparacion siniestro',
			key: 'reparacion_siniestro',
			type: 'number',
			value: '',
			is_price: true,
			show: true,
		},
		{
			text: 'Numero siniestro',
			key: 'numero_siniestro',
			type: 'text',
			value: '',
			show: true,
		},
	],
	singular_model_name_spanish: 'Siniestro',
	plural_model_name_spanish: 'Siniestros',
	create_model_name_spanish: 'Nuevo',
	text_delete: 'el',
}